import { useState } from "react";
import {
  FileText,
  Send,
  CheckCircle,
  AlertTriangle,
  Search,
  MoreVertical
} from "lucide-react";

import Card from "../components/Card";
import Badge from "../components/Badge";
import "./SuperAdminInvoices.css";

const SuperAdminInvoices = () => {
  const [searchTerm, setSearchTerm] = useState("");
  const [statusFilter, setStatusFilter] = useState("ALL");

  // Invoice data will come from the backend later.
  const invoices = [];

  const filteredInvoices = invoices.filter((invoice) => {
    const search = searchTerm.toLowerCase();

    const matchesSearch =
      invoice.invoiceNumber?.toLowerCase().includes(search) ||
      invoice.company?.toLowerCase().includes(search) ||
      invoice.supplier?.toLowerCase().includes(search);

    const matchesStatus =
      statusFilter === "ALL" ||
      invoice.status === statusFilter;

    return matchesSearch && matchesStatus;
  });

  const totalInvoices = invoices.length;

  const issuedInvoices = invoices.filter(
    (invoice) => invoice.status === "ISSUED"
  ).length;

  const paidInvoices = invoices.filter(
    (invoice) => invoice.status === "PAID"
  ).length;

  const overdueInvoices = invoices.filter(
    (invoice) => invoice.status === "OVERDUE"
  ).length;

  return (
    <div className="super-admin-invoices-page">

      {/* Header */}
      <div className="super-admin-invoices-header">
        <div>
          <h1>Invoices</h1>
          <p>
            View and monitor invoices across the ProcureHub platform.
          </p>
        </div>
      </div>

      {/* Summary Cards */}
      <div className="super-admin-invoices-summary">

        <Card className="super-admin-invoices-summary-card">
          <div className="super-admin-invoices-card-content">
            <div>
              <p>Total Invoices</p>
              <h2>{totalInvoices}</h2>
            </div>

            <div className="super-admin-invoices-icon blue">
              <FileText size={22} />
            </div>
          </div>
        </Card>

        <Card className="super-admin-invoices-summary-card">
          <div className="super-admin-invoices-card-content">
            <div>
              <p>Issued Invoices</p>
              <h2>{issuedInvoices}</h2>
            </div>

            <div className="super-admin-invoices-icon orange">
              <Send size={22} />
            </div>
          </div>
        </Card>

        <Card className="super-admin-invoices-summary-card">
          <div className="super-admin-invoices-card-content">
            <div>
              <p>Paid Invoices</p>
              <h2>{paidInvoices}</h2>
            </div>

            <div className="super-admin-invoices-icon green">
              <CheckCircle size={22} />
            </div>
          </div>
        </Card>

        <Card className="super-admin-invoices-summary-card">
          <div className="super-admin-invoices-card-content">
            <div>
              <p>Overdue Invoices</p>
              <h2>{overdueInvoices}</h2>
            </div>

            <div className="super-admin-invoices-icon red">
              <AlertTriangle size={22} />
            </div>
          </div>
        </Card>

      </div>

      {/* Invoice List */}
      <Card className="super-admin-invoices-table-card">

        <div className="super-admin-invoices-section-header">
          <div>
            <h2>Invoice List</h2>
            <p>
              Monitor invoices generated by suppliers across the platform.
            </p>
          </div>
        </div>

        {/* Search and Filter */}
        <div className="super-admin-invoices-toolbar">

          <div className="super-admin-invoices-search">
            <Search size={18} />

            <input
              type="text"
              placeholder="Search invoice, company or supplier..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </div>

          <select
            className="super-admin-invoices-filter"
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
          >
            <option value="ALL">All Status</option>
            <option value="DRAFT">Draft</option>
            <option value="ISSUED">Issued</option>
            <option value="PARTIALLY_PAID">
              Partially Paid
            </option>
            <option value="PAID">Paid</option>
            <option value="OVERDUE">Overdue</option>
            <option value="CANCELLED">Cancelled</option>
          </select>

        </div>

        {/* Table */}
        <div className="super-admin-invoices-table-wrapper">

          <table className="super-admin-invoices-table">

            <thead>
              <tr>
                <th>Invoice ID</th>
                <th>Company</th>
                <th>Supplier</th>
                <th>Invoice Date</th>
                <th>Due Date</th>
                <th>Amount</th>
                <th>Status</th>
                <th>Action</th>
              </tr>
            </thead>

            <tbody>

              {filteredInvoices.length > 0 ? (
                filteredInvoices.map((invoice) => (
                  <tr key={invoice.id}>

                    <td>
                      <strong>{invoice.invoiceNumber}</strong>
                    </td>

                    <td>{invoice.company}</td>
                    <td>{invoice.supplier}</td>
                    <td>{invoice.invoiceDate}</td>
                    <td>{invoice.dueDate}</td>
                    <td>₹{invoice.amount}</td>

                    <td>
                      <Badge
                        variant={
                          invoice.status === "PAID"
                            ? "success"
                            : invoice.status === "OVERDUE"
                            ? "danger"
                            : "warning"
                        }
                      >
                        {invoice.status}
                      </Badge>
                    </td>

                    <td>
                      <button
                        type="button"
                        className="super-admin-invoices-action"
                        aria-label={`Actions for ${invoice.invoiceNumber}`}
                      >
                        <MoreVertical size={18} />
                      </button>
                    </td>

                  </tr>
                ))
              ) : (
                <tr>
                  <td
                    colSpan="8"
                    className="super-admin-invoices-empty-cell"
                  >
                    <div className="super-admin-invoices-empty">

                      <FileText size={34} />

                      <h3>No invoices found</h3>

                      <p>
                        Supplier invoices will appear here once they
                        are generated.
                      </p>

                    </div>
                  </td>
                </tr>
              )}

            </tbody>

          </table>

        </div>

      </Card>

      {/* Information */}
      <Card className="super-admin-invoices-info">

        <div className="super-admin-invoices-info-icon">
          <FileText size={20} />
        </div>

        <div>
          <h3>About Invoices</h3>

          <p>
            Suppliers generate invoices for completed orders.
            Finance handles payment processing, while the Super Admin
            can monitor invoice activity across the platform.
          </p>
        </div>

      </Card>

    </div>
  );
};

export default SuperAdminInvoices;